# Generated by Django 5.2 on 2025-07-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standing",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
